"""Generates the sample DOCX templates shipped with this POC.

Run once (`python scripts/create_sample_templates.py`) to (re)create the
starter templates under `templates/`. Templates use docxtpl's Jinja2
syntax: `{{ field }}` for placeholders and `{%tr for ... %}` /
`{%tr endfor %}` for repeating table rows.

Real-world usage: these files would be authored directly in Word by a
business user, not generated by a script. This script exists purely so
the POC works end to end without requiring a hand-crafted .docx.
"""
from pathlib import Path

from docx import Document

TEMPLATES_DIR = Path(__file__).resolve().parents[1] / "templates"


def _add_heading(doc: Document, text: str) -> None:
    doc.add_heading(text, level=1)


def _add_field_line(doc: Document, label: str, jinja_expr: str) -> None:
    doc.add_paragraph(f"{label}: {{{{ {jinja_expr} }}}}")


def _add_line_items_table(doc: Document, columns: list[str]) -> None:
    # docxtpl's row-loop tags each need their own dedicated table row: a
    # row containing only `{%tr for ... %}`, then the data row that will
    # be repeated, then a row containing only `{%tr endfor %}`. docxtpl
    # strips the tag rows down to bare `{% for %}`/`{% endfor %}` markers
    # and duplicates the XML of the row sandwiched between them.
    table = doc.add_table(rows=4, cols=len(columns))
    table.style = "Light Grid Accent 1"

    header_cells = table.rows[0].cells
    for idx, column in enumerate(columns):
        header_cells[idx].text = column.replace("_", " ").title()

    table.rows[1].cells[0].text = "{%tr for item in line_items %}"

    data_cells = table.rows[2].cells
    for idx, column in enumerate(columns):
        data_cells[idx].text = f"{{{{ item.{column} }}}}"

    table.rows[3].cells[0].text = "{%tr endfor %}"


def build_invoice() -> None:
    doc = Document()
    _add_heading(doc, "INVOICE")
    _add_field_line(doc, "Invoice Number", "invoice_number")
    _add_field_line(doc, "Issue Date", "issue_date")
    _add_field_line(doc, "Due Date", "due_date")
    _add_field_line(doc, "Bill To", "customer_name")
    doc.add_paragraph("")
    doc.add_paragraph("Line Items:")
    _add_line_items_table(doc, ["description", "quantity", "unit_price", "total"])
    doc.add_paragraph("")
    _add_field_line(doc, "Subtotal", "subtotal")
    _add_field_line(doc, "Tax", "tax")
    _add_field_line(doc, "Total Due", "total_due")
    doc.save(TEMPLATES_DIR / "invoice_v1.docx")


def build_quote() -> None:
    doc = Document()
    _add_heading(doc, "QUOTE")
    _add_field_line(doc, "Quote Number", "quote_number")
    _add_field_line(doc, "Valid Until", "valid_until")
    _add_field_line(doc, "Prepared For", "customer_name")
    doc.add_paragraph("")
    doc.add_paragraph("Quoted Items:")
    _add_line_items_table(doc, ["description", "quantity", "unit_price", "total"])
    doc.add_paragraph("")
    _add_field_line(doc, "Estimated Total", "estimated_total")
    doc.save(TEMPLATES_DIR / "quote_v1.docx")


def build_purchase_order() -> None:
    doc = Document()
    _add_heading(doc, "PURCHASE ORDER")
    _add_field_line(doc, "PO Number", "po_number")
    _add_field_line(doc, "Order Date", "order_date")
    _add_field_line(doc, "Vendor", "vendor_name")
    _add_field_line(doc, "Ship To", "ship_to_address")
    doc.add_paragraph("")
    doc.add_paragraph("Items Ordered:")
    _add_line_items_table(doc, ["description", "quantity", "unit_price", "total"])
    doc.add_paragraph("")
    _add_field_line(doc, "Order Total", "order_total")
    doc.save(TEMPLATES_DIR / "purchase_order_v1.docx")


def build_contract() -> None:
    doc = Document()
    _add_heading(doc, "SERVICE CONTRACT")
    _add_field_line(doc, "Contract Number", "contract_number")
    _add_field_line(doc, "Effective Date", "effective_date")
    _add_field_line(doc, "Party A", "party_a_name")
    _add_field_line(doc, "Party B", "party_b_name")
    doc.add_paragraph("")
    doc.add_paragraph("Terms:")
    doc.add_paragraph("{{ terms_text }}")
    doc.add_paragraph("")
    _add_field_line(doc, "Contract Value", "contract_value")
    doc.save(TEMPLATES_DIR / "contract_v1.docx")


def build_memo_source() -> Path:
    """Builds the *source* .docx for templates/memo_v1.doc.

    memo_v1.doc (legacy binary Word format, demonstrating .doc template
    support alongside .docx — see docs/design-decisions.md ADR-013) is a
    checked-in binary file, not regenerated by `main()` below: python-docx
    can only write the modern OOXML .docx format, not the legacy binary
    one, so producing the final .doc requires LibreOffice. This function
    is provided for maintainers who need to regenerate it; it is not
    called automatically.

    To regenerate templates/memo_v1.doc from scratch:
        python -c "from scripts.create_sample_templates import build_memo_source; build_memo_source()"
        docker compose exec api soffice --headless --norestore --convert-to doc \\
            --outdir /app/templates /app/templates/_memo_v1_source.docx
        mv templates/_memo_v1_source.doc templates/memo_v1.doc
        rm templates/_memo_v1_source.docx
    """
    doc = Document()
    _add_heading(doc, "MEMO")
    _add_field_line(doc, "To", "recipient")
    _add_field_line(doc, "From", "author")
    _add_field_line(doc, "Subject", "subject")
    doc.add_paragraph("")
    doc.add_paragraph("{{ body }}")
    source_path = TEMPLATES_DIR / "_memo_v1_source.docx"
    doc.save(source_path)
    return source_path


def main() -> None:
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    build_invoice()
    build_quote()
    build_purchase_order()
    build_contract()
    print(f"Sample templates written to {TEMPLATES_DIR}")
    print(
        "Note: templates/memo_v1.doc (legacy .doc format) is a checked-in "
        "binary and not touched by this script — see build_memo_source()."
    )


if __name__ == "__main__":
    main()
